name: Run runbook-sync-downstream (reopen and update closed PRs)

on:
  workflow_dispatch:

jobs:
  runbook_sync_downstream:
    name: Run runbook-sync-downstream (reopen and update closed PRs)
    if: (github.repository == 'kubevirt/monitoring')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '1.22'

      - name: Run runbook-sync-downstream
        run: DRY_RUN=false SHOULD_REOPEN_AND_UPDATE_CLOSED_PRS=true GITHUB_TOKEN=${{ secrets.HCO_BOT_TOKEN }} make runbook-sync-downstream
